<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\Pivot;
use Illuminate\Support\Str;

class ProjectUser extends Pivot
{
    public $incrementing = false;
    public $timestamps = false;
    protected $table = 'project_user';
    protected $fillable = [
        'project_id',
        'user_id',
        'is_favorite',
        'is_manager',
        'settings',
    ];
    protected $casts = ['is_manager' => 'boolean'];

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
        self::creating(function (self $model) {
            $order = (int) ProjectUser::query()
                ->where('user_id', $model->user_id)
                ->max('order') + 1;
            $model->order = $order;
        });
    }

    /**
     * @return BelongsTo
     */
    public function project(): BelongsTo
    {
        return $this->belongsTo(Project::class);
    }

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}
